In [1]:
# KERAS FUNCTIONAL API USING MNIST(DEPLOYEABLE)

In [1]:
import pandas as pd
import numpy as np

np.random.seed(1212)

import keras
from keras.models import Model
from keras.layers import *
from keras import optimizers

In [3]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [4]:
df_train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df_test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df_features = df_train.iloc[:, 1:785]
df_label = df_train.iloc[:, 0]

In [9]:
X_test = df_test.iloc[:, 0:784]
X_test

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
print(X_test.shape)

(28000, 784)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_cv, y_train, y_cv = train_test_split(df_features, df_label, test_size = 0.2,random_state = 1212)

In [13]:
X_train = X_train.to_numpy().reshape(X_train.shape[0], 784)
X_cv = X_cv.to_numpy().reshape(X_cv.shape[0], 784)

In  MNIST data We reshape training dataset X_train into (33600, 784) and testing dataset X_cv (8400, 784) so each image  
becomes a flat input vector


The original dataset has 28000 rows (images) and 784 columns (pixels), 
but using 33600 and 8400 rows means you likely split  the data into training and testing sets

We split data into training and test sets to check if the model learns general patterns instead of just memorizing 
the training data to avoid overfitting

Rule to choose rows for training and tewstinf datasets : commonly 70–90% for training and 10–30% for testing depending 
on dataset size.

so  for training    70 % of 28,000 = 19,600 rows    an  for testing    30% of 28000 = 8400 rows

but actual rows used during reshape in training datasets is 33600 
It means 33600-19600 = 14000 rows were increased in your training data
It means Each original image was transformed to create new images to increase training data by ~50%
This is called data augmentation

In [14]:
X_test = X_test.to_numpy().reshape(28000, 784)
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
print((min(X_train[1]), max(X_train[1])))

(0.0, 255.0)

Meaning (short & clear):
0 → minimum value in X_train[1]
255 → maximum value in X_train[1]

Range 0–255 usually means:
It is image pixel data
0 = black
255 = white

In [16]:
# Feature Normalization
X_train = X_train.astype('float32'); 
X_cv= X_cv.astype('float32'); 
X_test = X_test.astype('float32')

X_train /= 255; 
X_cv /= 255; 
X_test /= 255

" We perform normalization to Speed up  model training"
" It Keeps values in a small range (0–1) and Improves numerical stability "
" Ensures equal importance of features that Leads to better model performance"

In [17]:
num_digits = 10
y_train = keras.utils.to_categorical(y_train, num_digits)
y_cv = keras.utils.to_categorical(y_cv, num_digits)

# a label is the correct answer/output for a given input.
# Training label → correct output during learning
# Validation label → correct output during checking

In [18]:
print(y_train[0]) 
print(y_train[3])

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]

In [19]:
# Input Parameters
n_input = 784 
n_hidden_1 = 300
n_hidden_2 = 100
n_hidden_3 = 100
n_hidden_4 = 200
num_digits = 10

In [20]:
Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

Simple overall meaning:

👉 You are building a deep neural network with:

1 input layer (784 features)
4 hidden layers (ReLU activation)
1 output layer (Softmax for classification)

In [21]:
model = Model(Inp, output)
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_1 (Dense)          │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_2 (Dense)          │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_3 (Dense)          │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_4 (Dense)          │ (None, 200)            │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 10)             │         2,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 297,910 (1.14 MB)

 Trainable params: 297,910 (1.14 MB)

 Non-trainable params: 0 (0.00 B)

In [22]:
# Insert Hyperparameters
training_epochs = 20
batch_size = 100
sgd = optimizers.SGD(learning_rate = 0.1)

In [23]:
# We rely on the plain vanilla Stochastic Gradient Descent as our optimizing methodology

model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

training_result1 = model.fit(X_train, y_train,
                     batch_size = batch_size,
                     epochs = training_epochs,
                     verbose = 2,
                     validation_data=(X_cv, y_cv))

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/20
280/280 - 4s - 14ms/step - accuracy: 0.4312 - loss: 1.9265 - val_accuracy: 0.7295 - val_loss: 1.1748
Epoch 2/20
280/280 - 3s - 10ms/step - accuracy: 0.8133 - loss: 0.7274 - val_accuracy: 0.8617 - val_loss: 0.5022
Epoch 3/20
280/280 - 3s - 11ms/step - accuracy: 0.8737 - loss: 0.4447 - val_accuracy: 0.8913 - val_loss: 0.3864
Epoch 4/20
280/280 - 3s - 9ms/step - accuracy: 0.8955 - loss: 0.3652 - val_accuracy: 0.9050 - val_loss: 0.3344
Epoch 5/20
280/280 - 3s - 10ms/step - accuracy: 0.9065 - loss: 0.3222 - val_accuracy: 0.9070 - val_loss: 0.3138
Epoch 6/20
280/280 - 3s - 9ms/step - accuracy: 0.9148 - loss: 0.2929 - val_accuracy: 0.9173 - val_loss: 0.2808
Epoch 7/20
280/280 - 3s - 9ms/step - accuracy: 0.9208 - loss: 0.2704 - val_accuracy: 0.9224 - val_loss: 0.2646
Epoch 8/20
280/280 - 2s - 9ms/step - accuracy: 0.9270 - loss: 0.2505 - val_accuracy: 0.9247 - val_loss: 0.2585
Epoch 9/20
280/280 - 3s - 10ms/step - accuracy: 0.9315 - loss: 0.2334 - val_accuracy: 0.9318 - val_loss: 0.2377
Epoch 10/20
280/280 - 3s - 10ms/step - accuracy: 0.9381 - loss: 0.2181 - val_accuracy: 0.9348 - val_loss: 0.2235
Epoch 11/20
280/280 - 3s - 10ms/step - accuracy: 0.9406 - loss: 0.2047 - val_accuracy: 0.9370 - val_loss: 0.2174
Epoch 12/20
280/280 - 2s - 9ms/step - accuracy: 0.9441 - loss: 0.1932 - val_accuracy: 0.9404 - val_loss: 0.2050
Epoch 13/20
280/280 - 2s - 9ms/step - accuracy: 0.9478 - loss: 0.1818 - val_accuracy: 0.9414 - val_loss: 0.1955
Epoch 14/20
280/280 - 2s - 8ms/step - accuracy: 0.9501 - loss: 0.1726 - val_accuracy: 0.9443 - val_loss: 0.1870
Epoch 15/20
280/280 - 2s - 8ms/step - accuracy: 0.9528 - loss: 0.1623 - val_accuracy: 0.9457 - val_loss: 0.1820
Epoch 16/20
280/280 - 4s - 15ms/step - accuracy: 0.9553 - loss: 0.1545 - val_accuracy: 0.9467 - val_loss: 0.1748
Epoch 17/20
280/280 - 2s - 8ms/step - accuracy: 0.9589 - loss: 0.1453 - val_accuracy: 0.9490 - val_loss: 0.1719
Epoch 18/20
280/280 - 2s - 9ms/step - accuracy: 0.9598 - loss: 0.1385 - val_accuracy: 0.9514 - val_loss: 0.1700
Epoch 19/20
280/280 - 3s - 11ms/step - accuracy: 0.9624 - loss: 0.1314 - val_accuracy: 0.9500 - val_loss: 0.1606
Epoch 20/20
280/280 - 5s - 16ms/step - accuracy: 0.9646 - loss: 0.1249 - val_accuracy: 0.9544 - val_loss: 0.1601

In [24]:
Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

In [29]:
learning_rate = 0.001

adam = keras.optimizers.Adam(learning_rate=learning_rate)

model2 = Model(Inp, output)

model2.compile(
    loss='categorical_crossentropy',
    optimizer=adam,
    metrics=['accuracy']
)

In [30]:
training_result2 = model2.fit(X_train, y_train,
                     batch_size = batch_size,
                     epochs = training_epochs,
                     verbose = 2,
                     validation_data=(X_cv, y_cv))

Epoch 1/20
280/280 - 5s - 18ms/step - accuracy: 0.8862 - loss: 0.3738 - val_accuracy: 0.9529 - val_loss: 0.1628
Epoch 2/20
280/280 - 2s - 9ms/step - accuracy: 0.9591 - loss: 0.1349 - val_accuracy: 0.9626 - val_loss: 0.1231
Epoch 3/20
280/280 - 3s - 9ms/step - accuracy: 0.9733 - loss: 0.0872 - val_accuracy: 0.9634 - val_loss: 0.1182
Epoch 4/20
280/280 - 2s - 9ms/step - accuracy: 0.9813 - loss: 0.0595 - val_accuracy: 0.9709 - val_loss: 0.1034
Epoch 5/20
280/280 - 3s - 10ms/step - accuracy: 0.9860 - loss: 0.0451 - val_accuracy: 0.9680 - val_loss: 0.1131
Epoch 6/20
280/280 - 3s - 10ms/step - accuracy: 0.9887 - loss: 0.0352 - val_accuracy: 0.9676 - val_loss: 0.1269
Epoch 7/20
280/280 - 3s - 10ms/step - accuracy: 0.9914 - loss: 0.0278 - val_accuracy: 0.9709 - val_loss: 0.1129
Epoch 8/20
280/280 - 3s - 10ms/step - accuracy: 0.9928 - loss: 0.0232 - val_accuracy: 0.9666 - val_loss: 0.1247
Epoch 9/20
280/280 - 3s - 9ms/step - accuracy: 0.9902 - loss: 0.0284 - val_accuracy: 0.9694 - val_loss: 0.1200
Epoch 10/20
280/280 - 3s - 10ms/step - accuracy: 0.9954 - loss: 0.0144 - val_accuracy: 0.9701 - val_loss: 0.1346
Epoch 11/20
280/280 - 4s - 13ms/step - accuracy: 0.9922 - loss: 0.0234 - val_accuracy: 0.9663 - val_loss: 0.1457
Epoch 12/20
280/280 - 4s - 13ms/step - accuracy: 0.9936 - loss: 0.0188 - val_accuracy: 0.9703 - val_loss: 0.1384
Epoch 13/20
280/280 - 3s - 12ms/step - accuracy: 0.9941 - loss: 0.0171 - val_accuracy: 0.9700 - val_loss: 0.1375
Epoch 14/20
280/280 - 3s - 12ms/step - accuracy: 0.9944 - loss: 0.0186 - val_accuracy: 0.9686 - val_loss: 0.1390
Epoch 15/20
280/280 - 4s - 13ms/step - accuracy: 0.9952 - loss: 0.0158 - val_accuracy: 0.9761 - val_loss: 0.1106
Epoch 16/20
280/280 - 4s - 15ms/step - accuracy: 0.9964 - loss: 0.0112 - val_accuracy: 0.9741 - val_loss: 0.1262
Epoch 17/20
280/280 - 4s - 13ms/step - accuracy: 0.9986 - loss: 0.0044 - val_accuracy: 0.9757 - val_loss: 0.1425
Epoch 18/20
280/280 - 3s - 12ms/step - accuracy: 0.9963 - loss: 0.0127 - val_accuracy: 0.9689 - val_loss: 0.1401
Epoch 19/20
280/280 - 3s - 12ms/step - accuracy: 0.9952 - loss: 0.0147 - val_accuracy: 0.9751 - val_loss: 0.1266
Epoch 20/20
280/280 - 3s - 11ms/step - accuracy: 0.9960 - loss: 0.0127 - val_accuracy: 0.9743 - val_loss: 0.1281

In [31]:
# Model 2A

Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

In [32]:
adam = keras.optimizers.Adam(learning_rate =  0.01)
model2a = Model(Inp, output)

In [33]:
model2a.compile(loss='categorical_crossentropy',
                optimizer='adam',
                metrics=['accuracy'])

In [34]:
training_result2a = model2a.fit(X_train, y_train,
                        batch_size = batch_size,
                        epochs = training_epochs,
                        verbose = 2,
                        validation_data=(X_cv, y_cv))

Epoch 1/20
280/280 - 7s - 27ms/step - accuracy: 0.8824 - loss: 0.3802 - val_accuracy: 0.9526 - val_loss: 0.1625
Epoch 2/20
280/280 - 4s - 15ms/step - accuracy: 0.9611 - loss: 0.1305 - val_accuracy: 0.9591 - val_loss: 0.1475
Epoch 3/20
280/280 - 5s - 16ms/step - accuracy: 0.9746 - loss: 0.0829 - val_accuracy: 0.9654 - val_loss: 0.1222
Epoch 4/20
280/280 - 4s - 15ms/step - accuracy: 0.9821 - loss: 0.0592 - val_accuracy: 0.9731 - val_loss: 0.0931
Epoch 5/20
280/280 - 3s - 12ms/step - accuracy: 0.9847 - loss: 0.0452 - val_accuracy: 0.9676 - val_loss: 0.1139
Epoch 6/20
280/280 - 4s - 15ms/step - accuracy: 0.9892 - loss: 0.0325 - val_accuracy: 0.9733 - val_loss: 0.1049
Epoch 7/20
280/280 - 4s - 14ms/step - accuracy: 0.9912 - loss: 0.0283 - val_accuracy: 0.9659 - val_loss: 0.1334
Epoch 8/20
280/280 - 5s - 16ms/step - accuracy: 0.9929 - loss: 0.0211 - val_accuracy: 0.9706 - val_loss: 0.1115
Epoch 9/20
280/280 - 4s - 13ms/step - accuracy: 0.9941 - loss: 0.0183 - val_accuracy: 0.9727 - val_loss: 0.1162
Epoch 10/20
280/280 - 4s - 14ms/step - accuracy: 0.9923 - loss: 0.0227 - val_accuracy: 0.9667 - val_loss: 0.1446
Epoch 11/20
280/280 - 4s - 14ms/step - accuracy: 0.9930 - loss: 0.0217 - val_accuracy: 0.9724 - val_loss: 0.1133
Epoch 12/20
280/280 - 3s - 12ms/step - accuracy: 0.9957 - loss: 0.0134 - val_accuracy: 0.9707 - val_loss: 0.1274
Epoch 13/20
280/280 - 3s - 12ms/step - accuracy: 0.9965 - loss: 0.0104 - val_accuracy: 0.9683 - val_loss: 0.1433
Epoch 14/20
280/280 - 4s - 13ms/step - accuracy: 0.9946 - loss: 0.0158 - val_accuracy: 0.9693 - val_loss: 0.1549
Epoch 15/20
280/280 - 4s - 13ms/step - accuracy: 0.9938 - loss: 0.0190 - val_accuracy: 0.9664 - val_loss: 0.1471
Epoch 16/20
280/280 - 4s - 13ms/step - accuracy: 0.9947 - loss: 0.0155 - val_accuracy: 0.9711 - val_loss: 0.1362
Epoch 17/20
280/280 - 4s - 13ms/step - accuracy: 0.9974 - loss: 0.0079 - val_accuracy: 0.9736 - val_loss: 0.1297
Epoch 18/20
280/280 - 3s - 12ms/step - accuracy: 0.9964 - loss: 0.0120 - val_accuracy: 0.9711 - val_loss: 0.1474
Epoch 19/20
280/280 - 5s - 19ms/step - accuracy: 0.9952 - loss: 0.0149 - val_accuracy: 0.9697 - val_loss: 0.1527
Epoch 20/20
280/280 - 4s - 14ms/step - accuracy: 0.9945 - loss: 0.0160 - val_accuracy: 0.9721 - val_loss: 0.1442

# TRAINING MODEL BY CHANGING LEARNING RATE TO 0.5

In [35]:
# Model 2b

Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

In [36]:
adam = keras.optimizers.Adam(learning_rate =  0.5)
model2b = Model(Inp, output)

In [37]:
model2b.compile(loss='categorical_crossentropy',
                optimizer='adam',
                metrics=['accuracy'])

In [38]:
training_result2b = model2b.fit(X_train, y_train,
                        batch_size = batch_size,
                        epochs = training_epochs,
                        validation_data=(X_cv, y_cv))

Epoch 1/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - accuracy: 0.8903 - loss: 0.3592 - val_accuracy: 0.9446 - val_loss: 0.1785
Epoch 2/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9594 - loss: 0.1317 - val_accuracy: 0.9539 - val_loss: 0.1514
Epoch 3/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.9741 - loss: 0.0831 - val_accuracy: 0.9670 - val_loss: 0.1116
Epoch 4/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9810 - loss: 0.0586 - val_accuracy: 0.9661 - val_loss: 0.1115
Epoch 5/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9834 - loss: 0.0492 - val_accuracy: 0.9703 - val_loss: 0.1037
Epoch 6/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.9898 - loss: 0.0332 - val_accuracy: 0.9729 - val_loss: 0.0996
Epoch 7/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9907 - loss: 0.0277 - val_accuracy: 0.9710 - val_loss: 0.1205
Epoch 8/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9934 - loss: 0.0213 - val_accuracy: 0.9693 - val_loss: 0.1242
Epoch 9/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9932 - loss: 0.0210 - val_accuracy: 0.9687 - val_loss: 0.1303
Epoch 10/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9911 - loss: 0.0271 - val_accuracy: 0.9713 - val_loss: 0.1141
Epoch 11/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9949 - loss: 0.0150 - val_accuracy: 0.9740 - val_loss: 0.1177
Epoch 12/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9941 - loss: 0.0170 - val_accuracy: 0.9737 - val_loss: 0.1200
Epoch 13/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9936 - loss: 0.0193 - val_accuracy: 0.9694 - val_loss: 0.1370
Epoch 14/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9949 - loss: 0.0139 - val_accuracy: 0.9719 - val_loss: 0.1318
Epoch 15/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9936 - loss: 0.0192 - val_accuracy: 0.9731 - val_loss: 0.1271
Epoch 16/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9968 - loss: 0.0108 - val_accuracy: 0.9703 - val_loss: 0.1490
Epoch 17/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.9959 - loss: 0.0134 - val_accuracy: 0.9709 - val_loss: 0.1415
Epoch 18/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9940 - loss: 0.0180 - val_accuracy: 0.9739 - val_loss: 0.1260
Epoch 19/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9985 - loss: 0.0046 - val_accuracy: 0.9763 - val_loss: 0.1312
Epoch 20/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9976 - loss: 0.0078 - val_accuracy: 0.9726 - val_loss: 0.1408

# TRAINING MODEL USING 5 HIDDEN LAYER

In [39]:
# Input Parameters
n_input = 784 # number of features
n_hidden_1 = 300
n_hidden_2 = 100
n_hidden_3 = 100
n_hidden_4 = 100
n_hidden_5 = 200
num_digits = 10

In [40]:
Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
x = Dense(n_hidden_5, activation='relu', name = "Hidden_Layer_5")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

In [41]:
model3 = Model(Inp, output)
model3.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)      │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_1 (Dense)          │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_2 (Dense)          │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_3 (Dense)          │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_4 (Dense)          │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_5 (Dense)          │ (None, 200)            │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 10)             │         2,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 308,010 (1.17 MB)

 Trainable params: 308,010 (1.17 MB)

 Non-trainable params: 0 (0.00 B)

In [42]:
adam = keras.optimizers.Adam(learning_rate = 0.01)
model3 = Model(Inp, output)

In [43]:

model3.compile(loss='categorical_crossentropy',
               optimizer='adam',
               metrics=['accuracy'])

In [44]:
training_result3 = model3.fit(X_train, y_train,
                      batch_size = batch_size,
                      epochs = training_epochs,
                      validation_data=(X_cv, y_cv))

Epoch 1/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - accuracy: 0.8863 - loss: 0.3828 - val_accuracy: 0.9506 - val_loss: 0.1676
Epoch 2/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.9591 - loss: 0.1332 - val_accuracy: 0.9560 - val_loss: 0.1473
Epoch 3/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.9736 - loss: 0.0868 - val_accuracy: 0.9643 - val_loss: 0.1179
Epoch 4/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.9810 - loss: 0.0611 - val_accuracy: 0.9663 - val_loss: 0.1167
Epoch 5/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9849 - loss: 0.0472 - val_accuracy: 0.9689 - val_loss: 0.1163
Epoch 6/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.9869 - loss: 0.0403 - val_accuracy: 0.9666 - val_loss: 0.1174
Epoch 7/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - accuracy: 0.9907 - loss: 0.0315 - val_accuracy: 0.9674 - val_loss: 0.1267
Epoch 8/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.9896 - loss: 0.0320 - val_accuracy: 0.9704 - val_loss: 0.1133
Epoch 9/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9904 - loss: 0.0302 - val_accuracy: 0.9727 - val_loss: 0.1127
Epoch 10/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.9931 - loss: 0.0217 - val_accuracy: 0.9726 - val_loss: 0.1126
Epoch 11/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9933 - loss: 0.0197 - val_accuracy: 0.9666 - val_loss: 0.1584
Epoch 12/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9928 - loss: 0.0226 - val_accuracy: 0.9737 - val_loss: 0.1207
Epoch 13/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9947 - loss: 0.0164 - val_accuracy: 0.9759 - val_loss: 0.1082
Epoch 14/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9942 - loss: 0.0178 - val_accuracy: 0.9713 - val_loss: 0.1513
Epoch 15/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9946 - loss: 0.0178 - val_accuracy: 0.9687 - val_loss: 0.1526
Epoch 16/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9950 - loss: 0.0152 - val_accuracy: 0.9724 - val_loss: 0.1280
Epoch 17/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9954 - loss: 0.0142 - val_accuracy: 0.9763 - val_loss: 0.1201
Epoch 18/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9967 - loss: 0.0093 - val_accuracy: 0.9764 - val_loss: 0.1106
Epoch 19/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9937 - loss: 0.0205 - val_accuracy: 0.9670 - val_loss: 0.1564
Epoch 20/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9955 - loss: 0.0137 - val_accuracy: 0.9761 - val_loss: 0.1171

#  TRAINING MODEL USING DROPOUTS IN NEURAL NETWORK

In [45]:
# Input Parameters
n_input = 784 
n_hidden_1 = 300
n_hidden_2 = 100
n_hidden_3 = 100
n_hidden_4 = 200
num_digits = 10

In [46]:
Inp = Input(shape=(784,))
x = Dense(n_hidden_1, activation='relu', name = "Hidden_Layer_1")(Inp)
x = Dropout(0.3)(x)
x = Dense(n_hidden_2, activation='relu', name = "Hidden_Layer_2")(x)
x = Dropout(0.3)(x)
x = Dense(n_hidden_3, activation='relu', name = "Hidden_Layer_3")(x)
x = Dropout(0.3)(x)
x = Dense(n_hidden_4, activation='relu', name = "Hidden_Layer_4")(x)
output = Dense(num_digits, activation='softmax', name = "Output_Layer")(x)

In [47]:
model4 = Model(Inp, output)
model4.summary()

Model: "functional_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)      │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_1 (Dense)          │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 300)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_2 (Dense)          │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_3 (Dense)          │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_4 (Dense)          │ (None, 200)            │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 10)             │         2,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 297,910 (1.14 MB)

 Trainable params: 297,910 (1.14 MB)

 Non-trainable params: 0 (0.00 B)

In [48]:
model4.compile(loss='categorical_crossentropy',
               optimizer='adam',
               metrics=['accuracy'])

In [49]:
result = model4.fit(X_train, y_train,
                     batch_size = batch_size,
                     epochs = training_epochs,
                     validation_data=(X_cv, y_cv))

Epoch 1/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.7960 - loss: 0.6315 - val_accuracy: 0.9353 - val_loss: 0.2187
Epoch 2/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9287 - loss: 0.2450 - val_accuracy: 0.9529 - val_loss: 0.1549
Epoch 3/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9449 - loss: 0.1878 - val_accuracy: 0.9593 - val_loss: 0.1354
Epoch 4/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9554 - loss: 0.1491 - val_accuracy: 0.9640 - val_loss: 0.1240
Epoch 5/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9618 - loss: 0.1274 - val_accuracy: 0.9676 - val_loss: 0.1155
Epoch 6/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9646 - loss: 0.1189 - val_accuracy: 0.9689 - val_loss: 0.1059
Epoch 7/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9707 - loss: 0.0980 - val_accuracy: 0.9709 - val_loss: 0.1093
Epoch 8/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9741 - loss: 0.0894 - val_accuracy: 0.9699 - val_loss: 0.1118
Epoch 9/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9744 - loss: 0.0862 - val_accuracy: 0.9723 - val_loss: 0.1009
Epoch 10/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9774 - loss: 0.0773 - val_accuracy: 0.9721 - val_loss: 0.1017
Epoch 11/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.9772 - loss: 0.0765 - val_accuracy: 0.9723 - val_loss: 0.1056
Epoch 12/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.9791 - loss: 0.0701 - val_accuracy: 0.9731 - val_loss: 0.1073
Epoch 13/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9808 - loss: 0.0648 - val_accuracy: 0.9746 - val_loss: 0.1044
Epoch 14/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9822 - loss: 0.0596 - val_accuracy: 0.9730 - val_loss: 0.1050
Epoch 15/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9816 - loss: 0.0586 - val_accuracy: 0.9750 - val_loss: 0.1041
Epoch 16/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9832 - loss: 0.0582 - val_accuracy: 0.9711 - val_loss: 0.1144
Epoch 17/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9846 - loss: 0.0496 - val_accuracy: 0.9729 - val_loss: 0.1125
Epoch 18/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.9846 - loss: 0.0516 - val_accuracy: 0.9739 - val_loss: 0.1066
Epoch 19/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9859 - loss: 0.0481 - val_accuracy: 0.9747 - val_loss: 0.1099
Epoch 20/20
280/280 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9860 - loss: 0.0459 - val_accuracy: 0.9750 - val_loss: 0.1105

In [50]:
test_pred = pd.DataFrame(model4.predict(X_test, batch_size=200))
test_pred = pd.DataFrame(test_pred.idxmax(axis = 1))
test_pred.index.name = 'ImageId'
test_pred = test_pred.rename(columns = {0: 'Label'}).reset_index()
test_pred['ImageId'] = test_pred['ImageId'] + 1

140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step

In [51]:
test_pred.head()

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3

In [53]:
test_pred.to_csv('mnist submission.csv', index = False)

# DEPLOYMENT — SAVE FINAL KERAS MODEL AS model.pkl

The original notebook code above is preserved unchanged. This deployment section uses the final trained `model4` model and saves the trained Keras Functional API model as `model.pkl` for Streamlit deployment.

**Recruiter test examples:** upload a 28×28 handwritten digit image or use the built-in sample digit buttons in the Streamlit app. Pixel values are converted to grayscale and scaled to 0–1, matching the notebook preprocessing.

In [54]:
# Save the FINAL trained model4 without changing the original training code.
import pickle
from pathlib import Path

deployment_model = model4
model_output_path = Path("model.pkl")

with open(model_output_path, "wb") as model_file:
    pickle.dump(deployment_model, model_file)

print("model.pkl saved successfully:")
print(model_output_path.resolve())
print("Model type:", type(deployment_model).__name__)

model.pkl saved successfully:
C:\Users\sarth\model.pkl
Model type: Functional

In [55]:
# Verify that model.pkl contains a usable Keras model.
with open("model.pkl", "rb") as model_file:
    loaded_deployment_model = pickle.load(model_file)

print("Loaded model type:", type(loaded_deployment_model).__name__)
print("Input shape:", loaded_deployment_model.input_shape)
print("Output shape:", loaded_deployment_model.output_shape)
print("predict() available:", hasattr(loaded_deployment_model, "predict"))

Loaded model type: Functional
Input shape: (None, 784)
Output shape: (None, 10)
predict() available: True

## Recruiter-friendly sample input examples

The deployed app includes built-in sample handwritten digits, so a recruiter can test predictions without the original `train.csv` or `test.csv` files. Manual upload accepts common image formats such as PNG and JPG. Recommended input: one centered handwritten digit on a simple background.

In [56]:
# Example deployment input using the already-prepared X_test array.
sample_input = X_test[:1].reshape(1, 784)
sample_prediction = model4.predict(sample_input, verbose=0)
print("Sample predicted digit:", int(np.argmax(sample_prediction[0])))
print("Sample confidence:", float(np.max(sample_prediction[0])))

Sample predicted digit: 2
Sample confidence: 1.0